# Generated by Django 4.1.3 on 2022-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studiomateapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(max_length=250),
        ),
    ]
