# Generated by Django 4.1.3 on 2022-12-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studiomateapi', '0004_alter_student_user_alter_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.CharField(default=240, max_length=50),
            preserve_default=False,
        ),
    ]
