# Generated by Django 4.1.3 on 2022-12-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studiomateapi', '0005_invoice_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
